exclude: '.venv|migrations'
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.9.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/hadialqattan/pycln
    rev: 0.0.1-beta.2
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8
