repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      exclude:
      - .venv/
      - migrations/
      - manage.py
      - instance.py
      - hook_main.py
      language_version: python3.7
