language: python
addons:
  apt:
    packages:
    - python-dev
    - libssl-dev
    - libffi-dev
python:
  - "2.7"
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- bash kubernetes/deployment/setup.sh
install:
- pip install -r requirements/tests.txt
# Environment variables
env:
- APP_CONFIG="config.TestingConfig" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_script:
  - psql -c 'create database test;' -U postgres
  - export DATABASE_URL=postgresql://postgres@localhost:5432/test
  - python manage.py initialize_db -c open_event_test_user@fossasia.org:fossasia
  - python manage.py runserver &
# command to run tests
script:
  - nosetests tests/unittests -v --with-coverage
  - robot tests/robot
# upload coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
  - codeclimate-test-reporter
  - bash kubernetes/deployment/deploy.sh
  - bash scripts/push_api_docs.sh
addons:
  code_climate:
    repo_token: 753e4b10e96f82079b5b1f4f89bb8b68db6ddfb048adaf4b9ee65dcbe9aece34
