language: python
  - "2.7"
# command to install dependencies
install: "pip install -r requirements/tests.txt"
# command to run tests
script: nosetests --with-coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
- coveralls
- codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 753e4b10e96f82079b5b1f4f89bb8b68db6ddfb048adaf4b9ee65dcbe9aece34
env:
  global:
  - secure: dlFxbSow93fYOx4TYWIlXkREKv9NjUbQ4W90dUBZxGH6ZW5K3pVeOiJ+9YbgSgE6/b0Eyi6zg/v3hpmWhWpSfqyv5KbF4/yZmJeZB8pnbG1HZaycap3bNj++KrGrN8aNx3sWAx7dyuMHqGMHGbnG42G8dMFoYXPUaXMjvMjNfB9WpAV7RQXQrHDwObq5bgE5IH7MU8Uwgcmq7rPAmvbpPfh8JHvsbwdR2juMryGFxuzudlJiZi68XOH3o3/KwZwiexM7p0kiSTgxvhfnuSFx06qBIF9FBuaGoCdY/Qjw8BK9MSyhGJSKPOJlVnoZtGjRPgNAypIXYZEYAH92CeQIG8DxnX2ecGizrR7B3mAFVlbaCPvALtTQ/V9folcUZQOepftjhHpyQEKB3wlGRSbeyFYDpQ9/7WyYu3p0d5ZSszh41XtIMmz8Gc4eOCPsZgmKF8+n2+n3WIQGOG2g5JvPqtcWjTZXXbrinu3pUjD00oVScor5kzLlVVw6odu7kc4lBgtF3R8PS1TK7pSuTQGNMaRpDwqaDwTvpV6P6G2jrzsw5gjJjdEOrHbgLT5PwMkCnJbJZJuqeqrrPDeoSsSw3IulzptJSUdJPDsspYTmcJNjcyhWyDGtWfGsrP2zf35j3KpZ3xz2t6NAst5AU0nhMNweI8VR62Cbij44twPO9IE=
  - secure: Xw7Jxfob6TQDnyy1vWAvgoQ6rZzd56Ll1LJVxsJ7ixyPmfW+at81Mswl2Bwo2gbOEM7+USZBM7VPdLoCG7fDolzrFeXR04SmCYjXDxdjfjNsNGanZvoVwutgpzXwpo6Up61mi8MgOqQKXGbImlNLB1zdjOMK+F1LT6H/JCqra+UnEUU6EtQeiQAbz6UsJ9nalquHWheHLv6nd2yfversdG/rNJ7Oxu3OQTbSanFh1w7N239wvU2qdV6oC1OaOc8YjHh80QX3FGeszD5g2SbMen4flYVlXFFRGmqUnYHejBDYHZAZnOHZ7Jzkbmn7UyOO9gmZrO/UCf/XfFBm3mFPkounheHi+RKGR6FCwCrT6aToPhwf942lC6uaWYIu7DBG1IceIOyqS2wThllg9eCIUGQNM7uX0gCBY4NJ1GhgJYJpEljZA8nGO7nCb2YW6WnshPdJZyRtECP4KYtatIRamruhAcMOPPJaAqWvEaRY1hktAotnEynex0fBi6FQoBvmiEo886rGBoJgsC//7qhu5se94l88KZtBPAzZUnm1G+1x3uXLFAZNAyrk0ZNDPPRm6GSVu3gu/CeM9o4vGt/EMtH7aQmqDAbm89t6fMUGNvQyKRhgD0+wUbrAA4HlFNNxm4YzzGrj9X7GFqbjIyTs39xvxUt73cPxUzC4Yj9Qr6g=
