version: '2'

services:

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=openevent
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openevent
    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:3-alpine
    command: redis-server
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - 127.0.0.1:6379:6379

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
        - discovery.type=single-node
    volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
        - 127.0.0.1:9200:9200
        - 127.0.0.1:9300:9300

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:test@postgres:5432/opev
      REDIS_URL: redis://redis:6379/0
      C_FORCE_ROOT: "true"
      SERVER_NAME: $SERVER_NAME
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./data/web:/open_event/static
    ports:
      - '80:5000'
