---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp:
      labels:
        service: redis
    spec:
      containers:
      - name: redis
        image: redis:3-alpine
        args:
        - redis-server
        ports:
        - containerPort: 6379
          protocol: TCP
      restartPolicy: Always
