server:
    url: https://github.com/maxlorenz/open-event-server
    branch: deployment
    container: web
    upgrade: bash scripts/upgrade.sh
    init: bash scripts/init.sh
frontend:
    url: https://github.com/fossasia/open-event-frontend
    branch: master
