name: Open Event Server

on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development

jobs:
  dredd:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: circleci/postgres:11.5-alpine-ram
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/tests.txt
    - name: Install Node Dependencies
      run: npm i aglio dredd@4
    - name: Create API blueprint
      run: npx aglio --input docs/api/api_blueprint_source.apib --compile --output docs/api/api_blueprint.apib
    - name: Test API Doc
      run: npx dredd
      env:
        APP_CONFIG: config.TestingConfig
        DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
        TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
